version: '3.3'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 8098:80
    links:
      - dota-api-laravel
    volumes:
      - ./dota-api-laravel/:/var/www/dota-api-laravel

  dota-api-laravel:
    container_name: dota-api-laravel
    build:
      context: .
      dockerfile: dota-api-laravel/Dockerfile
    volumes:
      - ./dota-api-laravel/:/var/www/dota-api-laravel
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
