version: '3.8'
services:
  php:
    container_name: dsb_php
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_POOL_NAME: "my-app_php"
      AUTORUN_LARAVEL_MIGRATION: "true"
    networks:
      - network
    volumes:
      - .:/var/www/html

  schedule:
    container_name: dsb_php_schedule
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "su", "root", "-c", "php artisan schedule:work" ]
    environment:
      PHP_POOL_NAME: "my-app_schedule"
    networks:
      - network

  queue:
    container_name: dsb_php_queue
    restart: always
    build:
      context: .
    command:
      [
        "su",
        "root",
        "-c",
        "php artisan queue:work --tries=3"
      ]
    environment:
      PHP_POOL_NAME: "my-app_queue"
    networks:
      - network

  node:
    container_name: dsb_node
    build:
      context: ../discord-bot-node
      dockerfile: ../discord-bot-node/Dockerfile
    volumes:
      - ../discord-bot-node:/var/www/discord-bot-node
      - ../discord-bot-node/index.js:/var/www/discord-bot-node/index.js
      - ../discord-bot-node/package.json:/var/www/discord-bot-node/package.json
    networks:
      - network

  mysql:
    container_name: dsb_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - network

networks:
  network:
