version: '3.8'
services:
  mysql:
    container_name: dsb_mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - network

  php:
    container_name: dsb_php
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_POOL_NAME: "my-app_php"
      AUTORUN_LARAVEL_MIGRATION: "true"
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    networks:
      - network

  schedule:
    container_name: dsb_php_schedule
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "su", "root", "-c", "php artisan schedule:work" ]
    environment:
      PHP_POOL_NAME: "my-app_schedule"
    networks:
      - network

  queue:
    container_name: dsb_php_queue
    restart: always
    build:
      context: .
    command:
      [
        "su",
        "root",
        "-c",
        "php artisan queue:work --tries=3"
      ]
    environment:
      PHP_POOL_NAME: "my-app_queue"
    networks:
      - network

  node:
    container_name: dsb_node_bot
    build:
      context: ../discord-bot-node
      dockerfile: ../discord-bot-node/Dockerfile.dev
    volumes:
      - ../discord-bot-node:/var/www/discord-bot-node
    ports:
      - 8989:8989
    networks:
      - network

  img_gen_node:
    container_name: dsb_img_gen_node
    build:
      context: ../img-gen-node
      dockerfile: ../img-gen-node/Dockerfile.dev
    volumes:
      - ../img-gen-node:/usr/src/app
    ports:
      - 8090:8090
    networks:
      - network

networks:
  network:
