version: '3.8'
services:
  php:
    container_name: dsb_php
    ports:
      - 3000:80
    build:
      context: .
    environment:
      - AUTORUN_LARAVEL_MIGRATION=true
    networks:
      - network

  node:
    container_name: dsb_node
    build:
      context: ../discord-bot-node
      dockerfile: ../discord-bot-node/Dockerfile
    volumes:
      - ../discord-bot-node:/var/www/discord-bot-node
      - ../discord-bot-node/index.js:/var/www/discord-bot-node/index.js
      - ../discord-bot-node/package.json:/var/www/discord-bot-node/package.json
    ports:
      - "80:8080"
    networks:
      - network

  mysql:
    container_name: dsb_mysql
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - network

networks:
  network:
