version: '3.8'
services:
  php:
    container_name: dsb_php
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PHP_POOL_NAME: "my-app_php"
      AUTORUN_LARAVEL_MIGRATION: "true"
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    networks:
      - network

  schedule:
    container_name: dsb_php_schedule
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "su", "root", "-c", "php artisan schedule:work" ]
    environment:
      PHP_POOL_NAME: "my-app_schedule"
    networks:
      - network

  queue:
    container_name: dsb_php_queue
    restart: always
    build:
      context: .
    command:
      [
        "su",
        "root",
        "-c",
        "php artisan queue:work --tries=3"
      ]
    environment:
      PHP_POOL_NAME: "my-app_queue"
    networks:
      - network

  bot_node:
    container_name: dsb_bot_node
    build:
      context: ../discord-bot-node
      dockerfile: ../discord-bot-node/Dockerfile
    ports:
      - 8020:8020
    networks:
      - network

  img_gen_node:
    container_name: dsb_img_gen_node
    build:
      context: ../img-gen-node
      dockerfile: ../img-gen-node/Dockerfile
    ports:
      - 8010:8010
    networks:
      - network

networks:
  network:
