version: '3.3'

services:
  nginx:
    container_name: nginx
    build:
      context: ../nginx
      dockerfile: ../nginx/Dockerfile
    ports:
      - 8098:80
    networks:
      - network
    volumes:
      - ../nginx:/var/www/dota-api-laravel

  dota-api-laravel:
    container_name: dota-api-laravel
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/dota-api-laravel
    networks:
      - network

  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    networks:
      - network

networks:
  network:
