name: Deploy Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy sources to server
        run: rsync -avz ./ root@${{ secrets.SSH_HOST }}:/home/ci/apps/dsb_fresh
      - name: Build & run application
        run: >-
          ssh root@${{ secrets.SSH_HOST }}
          '
            uptime;
            cd /home/ci/apps;
            rm -rf dsb_prev;
            mv dsb dsb_prev;
            mv dsb_fresh dsb;
            cp envs/dsb.node.env dsb/discord-bot-node/.env;
            cp envs/dsb.php.env dsb/dota-api-laravel/.env;
            cp envs/dsb.img-gen.env dsb/img-gen-node/.env;
            cd dsb/dota-api-laravel;
            docker compose build --no-cache;
            docker compose up -d --remove-orphans;
          '
